---
- name: Full Deploy VPN Node
  hosts: all
  become: yes
  gather_facts: no

  vars:
    # Эти переменные прилетят из Go (runner.go)
    master_url: ""
    priv_key: ""
    node_role: ""

  tasks:
    - name: Установка зависимостей
      apt:
        name: [curl, jq, ufw]
        state: present
        update_cache: yes

    - name: Установка Xray
      shell: bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install

    - name: Создание папок для Агента
      file:
        path: /etc/vpn-agent
        state: directory
        mode: '0755'

    - name: Копирование бинарника Агента
      # Мы предполагаем, что ты скомпилировал его заранее в папку build/
      copy:
        src: ../build/agent_linux_amd64
        dest: /usr/local/bin/vpn-agent
        mode: '0755'

    - name: Создание конфигурации .env
      copy:
        dest: /etc/vpn-agent/.env
        content: |
          MASTER_URL={{ master_url }}
          PRIVATE_KEY={{ priv_key }}
          NODE_ROLE={{ node_role }}
        mode: '0600'

    - name: Настройка systemd службы для Агента
      copy:
        dest: /etc/systemd/system/vpn-agent.service
        content: |
          [Unit]
          Description=VPN Cluster Agent
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/etc/vpn-agent
          ExecStart=/usr/local/bin/vpn-agent
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Запуск служб
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      loop:
        - xray
        - vpn-agent

    - name: Настройка фаервола
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: ['22', '443', '10085']