# ---
# - name: Deploy VPN Node (RU/EU)
#   hosts: all
#   become: yes
#   gather_facts: no # Ускоряет выполнение, не собирая лишнюю инфу об ОС

#   tasks:
#     - name: Установка базовых зависимостей
#       apt:
#         name:
#           - curl
#           - jq
#           - openssl
#           - ufw
#           - gnupg
#         state: present
#         update_cache: yes

#     - name: Установка Xray-core через официальный скрипт
#       shell: bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
#       args:
#         creates: /usr/local/bin/xray # Ansible пропустит шаг, если бинарник уже есть

#     - name: Фикс прав Xray (User=root)
#       replace:
#         path: /etc/systemd/system/xray.service
#         regexp: '^User=nobody'
#         replace: 'User=root'

#     - name: Создание рабочих директорий
#       file:
#         path: "{{ item }}"
#         state: directory
#         owner: root
#         group: root
#         mode: '0755'
#       loop:
#         - /usr/local/etc/xray
#         - /var/log/xray

#     - name: Перезагрузка systemd и старт Xray
#       systemd:
#         daemon_reload: yes
#         name: xray
#         state: restarted
#         enabled: yes

#     - name: Настройка UFW (Firewall)
#       ufw:
#         rule: allow
#         port: "{{ item }}"
#         proto: tcp
#       loop:
#         - "22"
#         - "443"
#         - "4433"
#         - "5000"
#       notify: Enable UFW

#   handlers:
#     - name: Enable UFW
#       ufw:
#         state: enabled
---
- name: Fake Deploy for Testing
  hosts: all
  gather_facts: no
  tasks:
    - name: Имитация установки пакетов (ждем 5 секунд)
      command: sleep 5
      delegate_to: localhost